server:
  port: 1080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # gateway配合服务发现，将路由按照服务名进行转发
      routes:
       - id: test_route1
         uri: lb://API # 与服务发现配合使用时必须使用大写的服务名，网络协议使用lb
         predicates:
           - Path=/api*
         filters:
           - RewritePath=/apitest,/api/test
           - RewritePath=/apibaiduimages2word,/api/baidu/images2word
eureka:
  client:
    service-url:
      defaultZone: http://liwei:wwwliwei001com@106.12.19.58:2080/eureka